/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
	| "Pacific/Midway"
	| "Pacific/Niue"
	| "Pacific/Honolulu"
	| "Pacific/Rarotonga"
	| "America/Anchorage"
	| "Pacific/Gambier"
	| "America/Los_Angeles"
	| "America/Tijuana"
	| "America/Denver"
	| "America/Phoenix"
	| "America/Chicago"
	| "America/Guatemala"
	| "America/New_York"
	| "America/Bogota"
	| "America/Caracas"
	| "America/Santiago"
	| "America/Buenos_Aires"
	| "America/Sao_Paulo"
	| "Atlantic/South_Georgia"
	| "Atlantic/Azores"
	| "Atlantic/Cape_Verde"
	| "Europe/London"
	| "Europe/Berlin"
	| "Africa/Lagos"
	| "Europe/Athens"
	| "Africa/Cairo"
	| "Europe/Moscow"
	| "Asia/Riyadh"
	| "Asia/Dubai"
	| "Asia/Baku"
	| "Asia/Karachi"
	| "Asia/Tashkent"
	| "Asia/Calcutta"
	| "Asia/Dhaka"
	| "Asia/Almaty"
	| "Asia/Jakarta"
	| "Asia/Bangkok"
	| "Asia/Shanghai"
	| "Asia/Singapore"
	| "Asia/Tokyo"
	| "Asia/Seoul"
	| "Australia/Brisbane"
	| "Australia/Sydney"
	| "Pacific/Guam"
	| "Pacific/Noumea"
	| "Pacific/Auckland"
	| "Pacific/Fiji";

export interface Config {
	auth: {
		users: UserAuthOperations;
		"payload-api-users": PayloadApiUserAuthOperations;
	};
	blocks: {};
	collections: {
		users: User;
		"payload-api-users": PayloadApiUser;
		media: Media;
		"blog-posts": BlogPost;
		"contact-us": ContactUs;
		"contact-partner": ContactPartner;
		"contact-promote": ContactPromote;
		"waiting-list": WaitingList;
		"payload-kv": PayloadKv;
		"payload-locked-documents": PayloadLockedDocument;
		"payload-preferences": PayloadPreference;
		"payload-migrations": PayloadMigration;
	};
	collectionsJoins: {};
	collectionsSelect: {
		users: UsersSelect<false> | UsersSelect<true>;
		"payload-api-users": PayloadApiUsersSelect<false> | PayloadApiUsersSelect<true>;
		media: MediaSelect<false> | MediaSelect<true>;
		"blog-posts": BlogPostsSelect<false> | BlogPostsSelect<true>;
		"contact-us": ContactUsSelect<false> | ContactUsSelect<true>;
		"contact-partner": ContactPartnerSelect<false> | ContactPartnerSelect<true>;
		"contact-promote": ContactPromoteSelect<false> | ContactPromoteSelect<true>;
		"waiting-list": WaitingListSelect<false> | WaitingListSelect<true>;
		"payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
		"payload-locked-documents":
			| PayloadLockedDocumentsSelect<false>
			| PayloadLockedDocumentsSelect<true>;
		"payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
		"payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
	};
	db: {
		defaultIDType: string;
	};
	fallbackLocale: ("false" | "none" | "null") | false | null | "en" | "en"[];
	globals: {
		"email-templates": EmailTemplate;
	};
	globalsSelect: {
		"email-templates": EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
	};
	locale: "en";
	user:
		| (User & {
				collection: "users";
		  })
		| (PayloadApiUser & {
				collection: "payload-api-users";
		  });
	jobs: {
		tasks: unknown;
		workflows: unknown;
	};
}
export interface UserAuthOperations {
	forgotPassword: {
		email: string;
		password: string;
	};
	login: {
		email: string;
		password: string;
	};
	registerFirstUser: {
		email: string;
		password: string;
	};
	unlock: {
		email: string;
		password: string;
	};
}
export interface PayloadApiUserAuthOperations {
	forgotPassword: {
		email: string;
		password: string;
	};
	login: {
		email: string;
		password: string;
	};
	registerFirstUser: {
		email: string;
		password: string;
	};
	unlock: {
		email: string;
		password: string;
	};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
	id: string;
	name?: string | null;
	roles?: ("super-admin" | "admin" | "editor")[] | null;
	updatedAt: string;
	createdAt: string;
	email: string;
	resetPasswordToken?: string | null;
	resetPasswordExpiration?: string | null;
	salt?: string | null;
	hash?: string | null;
	loginAttempts?: number | null;
	lockUntil?: string | null;
	sessions?:
		| {
				id: string;
				createdAt?: string | null;
				expiresAt: string;
		  }[]
		| null;
	password?: string | null;
}
/**
 * API-only users for Payload CMS external integrations (e.g., landing page accessing blog posts)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-api-users".
 */
export interface PayloadApiUser {
	id: string;
	/**
	 * Descriptive name for this Payload API user (e.g., 'Landing Page - Blog Reader')
	 */
	name: string;
	/**
	 * Purpose of this API user and where it's being used in the Payload CMS ecosystem
	 */
	description?: string | null;
	/**
	 * Allowed origins/domains for CORS (optional)
	 */
	allowedOrigins?:
		| {
				origin: string;
				id?: string | null;
		  }[]
		| null;
	updatedAt: string;
	createdAt: string;
	enableAPIKey?: boolean | null;
	apiKey?: string | null;
	apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
	id: string;
	alt: string;
	updatedAt: string;
	createdAt: string;
	url?: string | null;
	thumbnailURL?: string | null;
	filename?: string | null;
	mimeType?: string | null;
	filesize?: number | null;
	width?: number | null;
	height?: number | null;
	focalX?: number | null;
	focalY?: number | null;
	sizes?: {
		thumbnail?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
		card?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
		tablet?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
	};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
	id: string;
	title: string;
	/**
	 * SEO-friendly URL slug (auto-generated from title if not provided)
	 */
	slug: string;
	/**
	 * Short description for SEO and previews
	 */
	excerpt: string;
	content: {
		root: {
			type: string;
			children: {
				type: any;
				version: number;
				[k: string]: unknown;
			}[];
			direction: ("ltr" | "rtl") | null;
			format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
			indent: number;
			version: number;
		};
		[k: string]: unknown;
	};
	featuredImage?: (string | null) | Media;
	author: string | User;
	status: "draft" | "published";
	publishedAt?: string | null;
	seo?: {
		metaTitle?: string | null;
		metaDescription?: string | null;
		metaImage?: (string | null) | Media;
	};
	updatedAt: string;
	createdAt: string;
}
/**
 * Contact form submissions from the landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us".
 */
export interface ContactUs {
	id: string;
	fullName: string;
	email: string;
	companyName?: string | null;
	country?: string | null;
	industry?:
		| (
				| "Technology"
				| "Marketing"
				| "Finance"
				| "Healthcare"
				| "Education"
				| "Retail"
				| "Manufacturing"
				| "Consulting"
				| "Real Estate"
				| "Entertainment"
				| "Other"
				| "technology"
				| "finance"
				| "healthcare"
				| "education"
				| "manufacturing"
				| "retail"
				| "other"
		  )
		| null;
	otherIndustry?: string | null;
	message: string;
	/**
	 * Where did this submission come from?
	 */
	source?: ("landing-page" | "other") | null;
	/**
	 * Track the status of this inquiry
	 */
	status?: ("new" | "in-progress" | "resolved" | "spam") | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * Partner form submissions from the landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-partner".
 */
export interface ContactPartner {
	id: string;
	fullName: string;
	email: string;
	companyName: string;
	country: string;
	industry:
		| "Technology"
		| "Marketing"
		| "Finance"
		| "Healthcare"
		| "Education"
		| "Retail"
		| "Manufacturing"
		| "Consulting"
		| "Real Estate"
		| "Entertainment"
		| "Other"
		| "technology"
		| "finance"
		| "healthcare"
		| "education"
		| "manufacturing"
		| "retail"
		| "other";
	otherIndustry?: string | null;
	message: string;
	/**
	 * Where did this submission come from?
	 */
	source?: ("landing-page" | "other") | null;
	/**
	 * Track the status of this inquiry
	 */
	status?: ("new" | "in-progress" | "resolved" | "spam") | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * Promote form submissions from the landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-promote".
 */
export interface ContactPromote {
	id: string;
	fullName: string;
	email: string;
	companyName: string;
	country: string;
	industry:
		| "Technology"
		| "Marketing"
		| "Finance"
		| "Healthcare"
		| "Education"
		| "Retail"
		| "Manufacturing"
		| "Consulting"
		| "Real Estate"
		| "Entertainment"
		| "Other"
		| "technology"
		| "finance"
		| "healthcare"
		| "education"
		| "manufacturing"
		| "retail"
		| "other";
	otherIndustry?: string | null;
	message: string;
	/**
	 * Where did this submission come from?
	 */
	source?: ("landing-page" | "other") | null;
	/**
	 * Track the status of this inquiry
	 */
	status?: ("new" | "in-progress" | "resolved" | "spam") | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * Waiting list form submissions from the landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waiting-list".
 */
export interface WaitingList {
	id: string;
	/**
	 * Optional name of the user
	 */
	fullName?: string | null;
	email: string;
	/**
	 * Where did this submission come from?
	 */
	source?: ("landing-page" | "other") | null;
	/**
	 * Track if launch email has been sent
	 */
	status?: ("pending" | "notified") | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
	id: string;
	key: string;
	data:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
	id: string;
	document?:
		| ({
				relationTo: "users";
				value: string | User;
		  } | null)
		| ({
				relationTo: "payload-api-users";
				value: string | PayloadApiUser;
		  } | null)
		| ({
				relationTo: "media";
				value: string | Media;
		  } | null)
		| ({
				relationTo: "blog-posts";
				value: string | BlogPost;
		  } | null)
		| ({
				relationTo: "contact-us";
				value: string | ContactUs;
		  } | null)
		| ({
				relationTo: "contact-partner";
				value: string | ContactPartner;
		  } | null)
		| ({
				relationTo: "contact-promote";
				value: string | ContactPromote;
		  } | null)
		| ({
				relationTo: "waiting-list";
				value: string | WaitingList;
		  } | null);
	globalSlug?: string | null;
	user:
		| {
				relationTo: "users";
				value: string | User;
		  }
		| {
				relationTo: "payload-api-users";
				value: string | PayloadApiUser;
		  };
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
	id: string;
	user:
		| {
				relationTo: "users";
				value: string | User;
		  }
		| {
				relationTo: "payload-api-users";
				value: string | PayloadApiUser;
		  };
	key?: string | null;
	value?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
	id: string;
	name?: string | null;
	batch?: number | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
	name?: T;
	roles?: T;
	updatedAt?: T;
	createdAt?: T;
	email?: T;
	resetPasswordToken?: T;
	resetPasswordExpiration?: T;
	salt?: T;
	hash?: T;
	loginAttempts?: T;
	lockUntil?: T;
	sessions?:
		| T
		| {
				id?: T;
				createdAt?: T;
				expiresAt?: T;
		  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-api-users_select".
 */
export interface PayloadApiUsersSelect<T extends boolean = true> {
	name?: T;
	description?: T;
	allowedOrigins?:
		| T
		| {
				origin?: T;
				id?: T;
		  };
	updatedAt?: T;
	createdAt?: T;
	enableAPIKey?: T;
	apiKey?: T;
	apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
	alt?: T;
	updatedAt?: T;
	createdAt?: T;
	url?: T;
	thumbnailURL?: T;
	filename?: T;
	mimeType?: T;
	filesize?: T;
	width?: T;
	height?: T;
	focalX?: T;
	focalY?: T;
	sizes?:
		| T
		| {
				thumbnail?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
				card?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
				tablet?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
		  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
	title?: T;
	slug?: T;
	excerpt?: T;
	content?: T;
	featuredImage?: T;
	author?: T;
	status?: T;
	publishedAt?: T;
	seo?:
		| T
		| {
				metaTitle?: T;
				metaDescription?: T;
				metaImage?: T;
		  };
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us_select".
 */
export interface ContactUsSelect<T extends boolean = true> {
	fullName?: T;
	email?: T;
	companyName?: T;
	country?: T;
	industry?: T;
	otherIndustry?: T;
	message?: T;
	source?: T;
	status?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-partner_select".
 */
export interface ContactPartnerSelect<T extends boolean = true> {
	fullName?: T;
	email?: T;
	companyName?: T;
	country?: T;
	industry?: T;
	otherIndustry?: T;
	message?: T;
	source?: T;
	status?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-promote_select".
 */
export interface ContactPromoteSelect<T extends boolean = true> {
	fullName?: T;
	email?: T;
	companyName?: T;
	country?: T;
	industry?: T;
	otherIndustry?: T;
	message?: T;
	source?: T;
	status?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waiting-list_select".
 */
export interface WaitingListSelect<T extends boolean = true> {
	fullName?: T;
	email?: T;
	source?: T;
	status?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
	key?: T;
	data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
	document?: T;
	globalSlug?: T;
	user?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
	user?: T;
	key?: T;
	value?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
	name?: T;
	batch?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * Manage automated email templates for form submissions using MJML
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
	id: string;
	/**
	 * Send confirmation email to user when user joins waiting list
	 */
	waitingListEnabled?: boolean | null;
	waitingListSubject?: string | null;
	/**
	 * Leave empty to use default from environment (FROM_EMAIL)
	 */
	waitingListFromEmail?: string | null;
	waitingListFromName?: string | null;
	/**
	 * Write MJML here. Use {{name}} and {{email}} for dynamic values. HTML is compiled automatically on save.
	 */
	waitingListMjml?: string | null;
	waitingListTextBody?: string | null;
	waitingListHtmlBody?: string | null;
	/**
	 * Send confirmation email when user submits contact form
	 */
	contactFormEnabled?: boolean | null;
	contactFormSubject?: string | null;
	/**
	 * Leave empty to use default from environment (FROM_EMAIL)
	 */
	contactFormFromEmail?: string | null;
	contactFormFromName?: string | null;
	/**
	 * Write MJML here. Use {{name}}, {{email}}, {{message}} for dynamic values. HTML is compiled automatically on save.
	 */
	contactFormMjml?: string | null;
	contactFormTextBody?: string | null;
	contactFormHtmlBody?: string | null;
	updatedAt?: string | null;
	createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
	waitingListEnabled?: T;
	waitingListSubject?: T;
	waitingListFromEmail?: T;
	waitingListFromName?: T;
	waitingListMjml?: T;
	waitingListTextBody?: T;
	waitingListHtmlBody?: T;
	contactFormEnabled?: T;
	contactFormSubject?: T;
	contactFormFromEmail?: T;
	contactFormFromName?: T;
	contactFormMjml?: T;
	contactFormTextBody?: T;
	contactFormHtmlBody?: T;
	updatedAt?: T;
	createdAt?: T;
	globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
	[k: string]: unknown;
}

declare module "payload" {
	export interface GeneratedTypes extends Config {}
}
